from UI.MenuBuilder.Lab_5.Commands.SetCommands.SetColorArea1Command import SetColorArea1Command
from UI.MenuBuilder.Lab_5.Commands.SetCommands.SetColorArea2Command import SetColorArea2Command
from UI.MenuBuilder.Lab_5.Commands.SetCommands.SetColorArea3Command import SetColorArea3Command
from UI.MenuBuilder.Lab_5.Commands.SetCommands.SetShadowColorCommand import SetShadowColorCommand
from UI.MenuBuilder.Lab_5.Commands.SetCommands.SetSizeXCommand import SetSizeXCommand
from UI.MenuBuilder.Lab_5.Commands.SetCommands.SetSizeYCommand import SetSizeYCommand
from UI.MenuBuilder.Lab_5.Commands.SetCommands.SetSizeZCommand import SetSizeZCommand
from UI.MenuBuilder.Lab_5.Commands.SetCommands.SetSymbolColorCommand import SetSymbolColorCommand
from UI.MenuBuilder.Lab_5.Commands.SetCommands.SetScalingCommand import SetScalingCommand
