from UI.MenuBuilder.Lab_1 import MenuLab1
from UI.MenuBuilder.Lab_2 import MenuLab2
from UI.MenuBuilder.Lab_3 import MenuLab3
from UI.MenuBuilder.Lab_4 import MenuLab4
from UI.MenuBuilder.Lab_5 import MenuLab5
from UI.MenuBuilder.Lab_6 import MenuLab6
from UI.MenuBuilder.Lab_7 import MenuLab7
from UI.MenuBuilder.Lab_8 import MenuLab8
from UI.MenuBuilder.Exit import Exit
